### ISSUE TITLE
(feat) Alert user of new events

### ISSUE THREAD

**Issue by denzuko** [freecodecampdallas/freecodecampdallas.github.io#6]
As an android user
I would like to receive notifications of upcoming events
So that I may be informed of new meetups

Scenario: Push notification
Given I have the FCCDFW android app installed
When a new event shows up in the events atom feed
Then I should receive a push notification of the new event

**Comment by newswim** [comment]
need clarification on "atom feed"

**Comment by denzuko** [comment]
@newswim The old site had an atom feed for all articles and updates located freecodecamp.com/feed/

It was intended as an resource to leverage by newsreaders and the mobile app to have automatic updates.
